### ISSUE TITLE
Problem with empty folders

### ISSUE THREAD

**Issue by ismetanin** [surfstudio/Xcode-Project-Templates#23]
Currently we have a problem in the templates. Template generates a lot of empty folders but git [can't](https://stackoverflow.com/a/115992/5654667) add empty folders to repo and it means that our teammates will download project without some folder.

I think we have two ways to fix it:
1. Put .gitkeep file in each of folders
2. Leave it as is

**Comment by gregoryvit** [comment]
We need put .gitkeep in each folder if we really need these directories

**Comment by ismetanin** [comment]
@gregoryvit Okay, I'll fix it after fix #24
