### ISSUE TITLE
Add Readme generating

### ISSUE THREAD

**Issue by ismetanin** [surfstudio/Xcode-Project-Templates#35]
I think there will be good enchantment if we'll add readme generating.

Something like this:

# Project name
Little description
## Requirements
* iOS 10.0+
* Xcode 8.3
## Before running
For install all dependencies you should open project folder in **Terminal** and call: `make init`
## Module generation
Before generation you should open project folder in **Terminal**
* Screen generation: `make screen modName=[SCREEN_NAME]`

**Comment by gregoryvit** [comment]
I like it :)

**Comment by ismetanin** [comment]
Added in #36
